/*
 * Copyright 2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v15.0
processor: RW612
package_id: RW612ETA2I
mcu_data: ksdk2_0
processor_version: 0.15.4
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_io_mux.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: F3, peripheral: FLEXCOMM3, signal: USART_RXD, pin_signal: GPIO_24}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : 
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitPins(void)
{
	/* Enables the clock for the GPIO0 module */
	GPIO_PortInit(GPIO, 0);
//
	gpio_pin_config_t gpio0_pinD12_config = {
		.pinDirection = kGPIO_DigitalOutput,
		.outputLogic = 1U
	};

//	gpio_pin_config_t gpio0_pinD7_config = {
//		.pinDirection = kGPIO_DigitalInput,
//		.outputLogic = 0U
//	};
//
//	gpio_interrupt_config_t gpio0_pinD7_int_cfg = {
//		.mode = ,
//		.polarity =
//	};
//
//	GPIO_SetPinInterruptConfig(GPIO, 0U, 20U, );

//	/* Initialize GPIO functionality on pin PIO0_0 (pin D12)  */
	GPIO_PinInit(GPIO, 0U, 0U, &gpio0_pinD12_config);
	GPIO_PinInit(GPIO, 0U, 12U, &gpio0_pinD12_config);
	GPIO_PinInit(GPIO, 0U, 1U, &gpio0_pinD12_config);
//	GPIO_PinInit(GPIO, 0U, 20U, &gpio0_pinD7_config);

    /* Initialize FC3_USART_DATA functionality on pin GPIO_24 (pin F3) */
    IO_MUX_SetPinMux(IO_MUX_FC3_USART_DATA);

    IO_MUX_SetPinMux(IO_MUX_ENET_CLK);
    IO_MUX_SetPinMux(IO_MUX_ENET_RX);
    IO_MUX_SetPinMux(IO_MUX_ENET_TX);
    IO_MUX_SetPinMux(IO_MUX_ENET_MDIO);
    IO_MUX_SetPinMux(IO_MUX_GPIO21);
    IO_MUX_SetPinMux(IO_MUX_GPIO55);
    IO_MUX_SetPinMux(IO_MUX_GPIO20);

    /* Initialize CT0_MAT0_OUT functionality on pin GPIO_0 (pin M1) */
    IO_MUX_SetPinMux(IO_MUX_CT0_MAT0_OUT);

//    /* Initialize SCT_OUT_0 functionality on pin GPIO_3 (pin L4) */
//    IO_MUX_SetPinMux(IO_MUX_SCT_OUT_0);
//    /* Initialize SCT_OUT_1 functionality on pin GPIO_4 (pin N3) */
//    IO_MUX_SetPinMux(IO_MUX_SCT_OUT_1);

//    /* Initialize GPIO0 functionality on pin GPIO_0 (pin D12) */
//    IO_MUX_SetPinMux(IO_MUX_GPIO0);
    IO_MUX_SetPinMux(IO_MUX_GPIO1);
    IO_MUX_SetPinMux(IO_MUX_GPIO12);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
